name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3
  provider: ^6.1.2
  
  # API & Networking
  http: ^1.5.0
  
  # Security & Storage
  flutter_secure_storage: ^9.2.4
  local_auth: ^3.0.0
  local_auth_android: ^2.0.0
  
  # Configuration
  flutter_dotenv: ^5.2.1
  
  # UI/UX & Icons
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  lucide_flutter: ^0.546.0
  flutter_spinkit: ^5.2.2
  elegant_notification: ^2.5.1
  fl_chart: ^0.69.0

  easy_date_timeline: ^2.0.9 # <-- ĐÃ SỬA LẠI PHIÊN BẢN
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  lucide_icons: ^0.257.0
  
  # For export/import functionality
  file_picker: ^8.1.4
  share_plus: ^10.1.2
  path_provider: ^2.1.5
  flutter_heatmap_calendar: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

dependency_overrides:
  intl: 0.20.2